# Generated by Django 4.2.7 on 2024-01-27 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
